name: gtest
triggers:
  push:
    branches:
      - 'dev-sonic8.2.2'
  merge_request:
    target-branches:
      - 'dev-sonic8.2.2'

jobs:
  build-image-job:
    steps:
      - uses: checkout
        inputs:
          repository-url: 'https://github.com/CESNET/libyang.git'
          ref: 'v2.0.0'
          path: 'libyang'
      - uses: checkout # 1
        inputs:
          repository-url: 'https://github.com/google/googletest.git'
          ref: 'v1.16.x'
          path: 'googletest'
      - uses: checkout # 2
        inputs:
          path: 'alibgp-gtest'
      - run: cp -r $AONE_CI_SOURCE/libyang $AONE_CI_SOURCE/googletest $AONE_CI_SOURCE/alibgp-gtest/
      - run: |
         ls -al $AONE_CI_SOURCE/libyang
         ls -al $AONE_CI_SOURCE/googletest
         ls -al $AONE_CI_SOURCE/alibgp-gtest
      - uses: setup-env # 3
      - uses: build-image
        inputs:
          image-name: hub.docker.alibaba-inc.com/aone-base-global/gtest
          image-tag: latest
          context-dir: alibgp-gtest
          dockerfile-path: alibgp-gtest/docker/ubuntu20-gtest/Dockerfile

  run-gtest:
    name: gtest
    needs: build-image-job
    runs-on:
      - self-hosted
      - ECS-topotest
    steps:
      - run: |
          cd ~/frr/tests/gtest ; ./gtest_zebra_srte
        image: hub.docker.alibaba-inc.com/aone-base-global/gtest:latest
    timeout: 1h