name: topotest
triggers:
  push:
    branches:
      - '**'
  merge_request:
    target-branches:
      - '**'

jobs:
  build-image-job:
    steps:
      - uses: checkout
        inputs:
          repository-url: 'https://github.com/CESNET/libyang.git'
          ref: 'v2.0.0'
          path: 'libyang'
      - uses: checkout # 1
        inputs:
          path: 'alibgp'
      - run: cp -r $AONE_CI_SOURCE/libyang $AONE_CI_SOURCE/alibgp/
      - run: |
         ls -al $AONE_CI_SOURCE/libyang
         ls -al $AONE_CI_SOURCE/alibgp
      - uses: setup-env # 2
      - uses: build-image
        inputs:
          image-name: hub.docker.alibaba-inc.com/aone-base-global/topotest
          image-tag: latest
          context-dir: alibgp
          dockerfile-path: alibgp/docker/ubuntu20-ci/Dockerfile

  run-topotest:
    name: topotest
    needs: build-image-job
    runs-on:
      - self-hosted
      - ECS-topotest
    steps:
      - run: |
          cd ~/frr/tests/topotests ; sudo pytest -m esr --html=/tmp/frrpytest.html -n 8
        image: hub.docker.alibaba-inc.com/aone-base-global/topotest:latest
        container:
          options: '--rm --init --privileged -v /lib/modules:/lib/modules -v /tmp/topotest_logs:/tmp'
    timeout: 2h