#ifndef TEST_MODEL_H
#define TEST_MODEL_H

#include <vector>
#include <string>
#include <cstdint>
#include <map>

struct srv6_sidlist_t {
	std::string sidlist_name;
	uint8_t weight;
	uint32_t flags;
#define SRV6_SID_LIST_BACKUP 0x10
	// segment omitted
};

// TODO: require every prefix_t to specify its family
struct prefix_t {
	// We follow big-endian representation for IPv6 addresses
	uint8_t family;
	uint16_t prefixlen;
	uint8_t endpoint[16];
};

struct api_policy_t {
	uint32_t color;
	struct prefix_t endpoint;
	std::vector<srv6_sidlist_t> sidlists;
};

enum policy_status_t { INIT = 0, DOWN, UP };

struct rnh_t {
	struct prefix_t prefix;
	struct prefix_t resolved_route;
	uint32_t srte_color;
};

struct policy_t {
	uint32_t color;
	struct prefix_t policy_table_key;
	policy_status_t status;
	std::vector<srv6_sidlist_t> segment_list;
	std::vector<rnh_t> nht;
};

struct srte_table_t {
	uint32_t color;
	std::vector<policy_t> policies;
};

struct nexthop_t {
	uint8_t gate[16];
	uint32_t color;

	/*
	 * For leaf type nexthop_t, sidlist_name is non-empty, resolved is
	 * empty.
	 *
	 * For root type nexthop_t, sidlist_name is empty, resolved is non-empty
	 * and contains only leaf-type members.
	 * */
	std::string sidlist_name;
	uint16_t flags;
#define NEXTHOP_FLAG_IS_BACKUP (1 << 9)
	std::vector<nexthop_t> resolved;
};

struct nhg_t {
	/*
	 * For sidlist-level nhg_t, nexthop is of leaf type, seg_depends is
	 * empty.
	 *
	 * For policy-level nhg_t, nexthop is of root type, seg_depends is
	 * non-empty and contains only sidlist-level members.
	 *
	 * For route-level nhg_t, shared_seg_depends is non-empty.
	 * */
	std::vector<nexthop_t> resolved_nexthops;
	std::vector<nhg_t> seg_depends;

	// Specify shape only, not for verbatim comparison with actual C states
	bool contains_id;
	int internal_id;
	std::vector<int> shared_seg_depends;
};

struct rnh_list_t {
	struct prefix_t prefix;
	std::vector<rnh_t> rnh;
};

struct nhe_t {
	uint8_t gate[16];
	uint32_t color;
};

struct api_route_t {
	struct prefix_t prefix;

	// Only useful in zapi_nexthop_update messages
	uint32_t srte_color;
	uint8_t srte_color_flag;

	std::vector<struct nhe_t> route_entry;
};

struct api_route_del_t {
	struct prefix_t prefix;
};

/*
 * Messages generated by zebra
 * */
struct msg_policy_status_t {
	uint32_t color;
	struct prefix_t prefix;
	uint32_t status;
};

struct msg_nexthop_update_t {
	struct prefix_t match;
	struct api_route_t nhr;
};

struct msg_t {
	uint16_t command;
	struct msg_policy_status_t policy_notify_status;
	struct msg_nexthop_update_t nexthop_update;
};

struct zebra_state_t {
	std::vector<srte_table_t> policy_route_table;
	std::vector<nhg_t> nhgs;
	std::vector<rnh_list_t> rnh_table;
	std::vector<api_route_t> rib;
};

struct test_case_policy_set_del_t {
	int test_id;
	struct zebra_state_t initial_state;
	struct api_policy_t input_policy;
	struct zebra_state_t final_state;
	std::vector<struct msg_t> msg_fifo;
};

struct test_case_route_add_t {
	int test_id;
	struct zebra_state_t initial_state;
	struct api_route_t input_route;
	struct zebra_state_t final_state;
	std::vector<struct msg_t> msg_fifo;
};

struct api_rnh_t {
	struct prefix_t prefix;
	uint32_t srte_color;
};

struct test_case_rnh_register {
	int test_id;
	struct zebra_state_t initial_state;
	struct api_rnh_t input_rnh;
	struct zebra_state_t final_state;
	std::vector<struct msg_t> msg_fifo;
};

struct test_case_route_del_t {
	int test_id;
	struct zebra_state_t initial_state;
	struct api_route_del_t input_route;
	struct zebra_state_t final_state;
	std::vector<struct msg_t> msg_fifo;
};

std::vector<test_case_policy_set_del_t>
read_all_test_cases_policy_set_del(const std::string &json_file_path);

std::map<int, test_case_policy_set_del_t>
read_policy_set_del_test_cases_map(const std::string &json_file_path);

std::vector<test_case_route_add_t>
read_all_test_cases_route_add(const std::string &json_file_path);

std::vector<test_case_rnh_register>
read_test_case_rnh_register_vec(const std::string &json_file_path);

std::map<int, test_case_rnh_register>
read_all_test_cases_nexthop_register(const std::string &json_file_path);

std::vector<test_case_route_del_t>
read_all_test_cases_route_del(const std::string &json_file_path);

std::string prefix_t2str(const struct prefix_t &p);
void print_nexthops(const struct nexthop_t &n);
void print_nhe(const struct nhe_t &nhe);
void print_api_policy(const struct api_policy_t &api_policy);
void print_api_rnh(const struct api_rnh_t &rnh);
void print_api_route(const struct api_route_t &route);
void print_api_route_del(const struct api_route_del_t &route);


/*
 * Multi-step test case
 * */

enum class Action {
	// API calls
	POLICY_SET,
	POLICY_DEL,
	ROUTE_ADD,
	ROUTE_DEL,
	RNH_REGISTER,
	RNH_UNREGISTER,
};

struct step_action_t {
	Action action;
	struct api_policy_t input_policy;
	struct rnh_t input_rnh;
	struct api_route_t input_route;
};

struct multi_test_case_t {
	int test_id;
	struct zebra_state_t initial_state;
	std::vector<struct step_action_t> input_actions;
	struct zebra_state_t final_state;
};


std::map<int, multi_test_case_t>
read_multi_test_cases_map(const std::string &json_file_path);

std::vector<multi_test_case_t>
read_multi_test_cases_vec(const std::string &json_file_path);



struct segment_t {
	uint32_t index;
	std::string v6Address;
};

struct segment_list_t {
	std::string name;
	uint16_t refCount;
	uint32_t flags;
	uint32_t status;
	bool installed;

	// sorted by index
	std::vector<segment_t> segments;
};

struct candidate_t {
	std::string candidate_name;
	std::string segment_list_name;
	uint32_t preference;
	uint32_t status;
};

struct path_policy_t {
	uint32_t color;
	std::string endpoint;
	uint32_t status;
	std::vector<struct candidate_t> candidate_paths;
};

struct pathd_state_t {
	// sorted by name
	std::vector<struct segment_list_t> segment_lists;
	std::vector<struct path_policy_t> policies;
};

struct api_segment_list_t {
	std::string name;
};

struct api_segment_list_segment_t {
	std::string name;
	uint32_t index;
	std::string v6Address;
};

struct api_no_segment_list_t {
	std::string name;
};

struct api_segment_list_no_segment_t {
	std::string name;
	uint32_t index;
};

struct api_srte_policy_t {
	uint32_t color;
	std::string endpoint;
};

struct api_srte_policy_candidate_path_t {
	uint32_t color;
	std::string endpoint;
	std::string candidate_name;
	uint32_t preference;
	std::string segment_list_name;
};

struct api_srte_no_policy_t {
	uint32_t color;
	std::string endpoint;
};

struct api_srte_policy_no_candidate_path_t {
	uint32_t color;
	std::string endpoint;
	uint32_t preference;
	std::string candidate_name;
};

struct test_case_segment_list_t {
	int test_id;
	struct pathd_state_t initial_state;
	struct api_segment_list_t input_segment_list;
	struct pathd_state_t final_state;
};

struct test_case_segment_list_segment_t {
	int test_id;
	struct pathd_state_t initial_state;
	struct api_segment_list_segment_t input_segment;
	struct pathd_state_t final_state;
};

struct test_case_no_segment_list_t {
	int test_id;
	struct pathd_state_t initial_state;
	struct api_no_segment_list_t input_segment_list;
	struct pathd_state_t final_state;
};

struct test_case_segment_list_no_segment_t {
	int test_id;
	struct pathd_state_t initial_state;
	struct api_segment_list_no_segment_t input_segment;
	struct pathd_state_t final_state;
};

struct test_case_srte_policy_t {
	int test_id;
	struct pathd_state_t initial_state;
	struct api_srte_policy_t input_policy;
	struct pathd_state_t final_state;
};

struct test_case_srte_policy_candidate_path_t {
	int test_id;
	struct pathd_state_t initial_state;
	struct api_srte_policy_candidate_path_t input_candidate_path;
	struct pathd_state_t final_state;
};

struct test_case_srte_no_policy_t {
	int test_id;
	struct pathd_state_t initial_state;
	struct api_srte_no_policy_t input_policy;
	struct pathd_state_t final_state;
};

struct test_case_srte_policy_no_candidate_path_t {
	int test_id;
	struct pathd_state_t initial_state;
	struct api_srte_policy_no_candidate_path_t input_candidate_path;
	struct pathd_state_t final_state;
};

std::map<int, struct test_case_segment_list_t>
read_segment_list_test_cases_map(const std::string &json_file_path);

std::vector<test_case_segment_list_t>
read_all_tests_segment_list(const std::string &json_file_path);

std::map<int, struct test_case_segment_list_segment_t>
read_segment_list_segment_test_cases_map(const std::string &json_file_path);

std::vector<struct test_case_segment_list_segment_t>
read_all_tests_segment(const std::string &json_file_path);

std::map<int, struct test_case_no_segment_list_t>
read_no_segment_list_test_cases_map(const std::string &json_file_path);

std::vector<test_case_no_segment_list_t>
read_all_tests_no_segment_list(const std::string &json_file_path);

std::map<int, struct test_case_segment_list_no_segment_t>
read_segment_list_no_segment_test_cases_map(const std::string &json_file_path);

std::vector<struct test_case_segment_list_no_segment_t>
read_all_tests_no_segment(const std::string &json_file_path);

std::map<int, struct test_case_srte_policy_t>
read_srte_policy_test_cases_map(const std::string &json_file_path);

std::vector<struct test_case_srte_policy_t>
read_all_tests_srte_policy(const std::string &json_file_path);

std::map<int, struct test_case_srte_policy_candidate_path_t>
read_srte_policy_candidate_path_test_cases_map(
	const std::string &json_file_path);

std::vector<struct test_case_srte_policy_candidate_path_t>
read_all_tests_srte_policy_candidate_path(const std::string &json_file_path);

std::map<int, struct test_case_srte_no_policy_t>
read_srte_no_policy_test_cases_map(const std::string &json_file_path);

std::vector<struct test_case_srte_no_policy_t>
read_all_tests_srte_no_policy(const std::string &json_file_path);

std::map<int, struct test_case_srte_policy_no_candidate_path_t>
read_srte_policy_no_candidate_path_test_cases_map(
	const std::string &json_file_path);

std::vector<struct test_case_srte_policy_no_candidate_path_t>
read_all_tests_srte_policy_no_candidate_path(const std::string &json_file_path);

#endif // TEST_MODEL_H
