FROM debian:buster

ENV DEBIAN_FRONTEND noninteractive
ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn

RUN apt-get update && \
    apt-get install -y apt-transport-https ca-certificates curl wget logrotate \
    libc-ares2 libjson-c3 vim procps libreadline7 gnupg2 lsb-release apt-utils rsync git \
    make autoconf binutils bison flex gpg install-info iputils-ping less libtool libjson-c-dev libreadline-dev libpcre2-8-0 lsof\
    libpython-dev libpython3-dev libcap-dev libelf-dev man pkg-config python-pip python3 python3-dev python3-sphinx python3-pytest \
    tcpdump tmux texinfo valgrind vim wget tini  net-tools libc-ares-dev \
    libsnmp-dev snmpd snmp sudo \
    libpcre2-dev cmake \
    mininet python-pip iproute2 iperf gdb && \
    pip install ipaddr && \
    pip install "pytest<5" && \
    pip install exabgp==3.4.17

RUN git clone https://github.com/CESNET/libyang.git && \
    cd libyang && \
    git checkout v2.0.0 && \
    mkdir build; cd build && \
    cmake -D CMAKE_INSTALL_PREFIX:PATH=/usr -D CMAKE_BUILD_TYPE:String="Release" .. && \
    make && make install
    
COPY docker/buster_dep /home
RUN cd /home && \
    dpkg -i libhiredis0.14_0.14.0-3~bpo9+1_amd64.deb && \
    dpkg -i libhiredis-dev_0.14.0-3~bpo9+1_amd64.deb && \
    dpkg -i libredisplusplus_1.0_amd64.deb && \
    dpkg -i libredisplusplus-dev_1.0_amd64.deb

RUN curl -s https://deb.frrouting.org/frr/keys.asc | apt-key add -
RUN echo deb https://deb.frrouting.org/frr $(lsb_release -s -c) frr-stable | tee -a /etc/apt/sources.list.d/frr.list

RUN apt-get update && \
    apt-get install -y frr frr-pythontools && \
    rm -rf /var/lib/apt/lists/*


RUN addgroup --system --gid 92 frr \
    && addgroup --system --gid 85 frrvty \
    && adduser --system --ingroup frr --home /var/run/frr/  --gecos "FRRouting suite" --shell /bin/false frr \
    && usermod -G frrvty frr \
&& useradd -d /var/run/exabgp/ -s /bin/false exabgp

RUN mkdir -p /var/run/frr
RUN chown -R frr:frr /etc/frr /var/run/frr

# Configure coredumps
RUN echo "" >> /etc/security/limits.conf; \
    echo "* soft core unlimited" >> /etc/security/limits.conf; \
    echo "root soft core unlimited" >> /etc/security/limits.conf; \
    echo "* hard core unlimited" >> /etc/security/limits.conf; \
    echo "root hard core unlimited" >> /etc/security/limits.conf

# Copy run scripts to facilitate users wanting to run the tests
COPY docker/inner /opt/topotests

ENV PATH "$PATH:/opt/topotests"

RUN echo "cat /opt/topotests/motd.txt" >> /root/.profile && \
      echo "export PS1='(topotests) $PS1'" >> /root/.profile

ENTRYPOINT [ "bash", "/opt/topotests/entrypoint.sh" ]
